language: clojure
jdk:
  - oraclejdk8
services:
  - redis-server
install:
  - wget -O boot https://github.com/boot-clj/boot/releases/download/2.0.0-rc4/boot.sh
  - chmod 755 boot
  - ./boot -V
script:
  - mkdir target
  - ./boot once